/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agricultureproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;


/**
 *
 * @author Neen
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    HashMap hm = new HashMap();
    DatabaseConnection dc = new DatabaseConnection();
    frameLogin login;
    
    public void setWindowView()
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public Main(String farmer_id, String memeber_type) 
    {
        initComponents();
        lblFarmerId.setText(farmer_id);
        lblFarmerType.setText(memeber_type);
        
        setWindowView();
        
        panelSwitch(pnlNotification);
        
    }
    
    
    public void tableBody(JTable table)
    {
        table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {

        public Component getTableCellRendererComponent(JTable table, 
                Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            Component c = super.getTableCellRendererComponent(table, 
                value, isSelected, hasFocus, row, column);
            c.setBackground(row%2==0 ? Color.LIGHT_GRAY : Color.white);                        
            return c;
        };
        });
    }
    
    public void tableHeader(JTable table)
    {
        JTableHeader header = table.getTableHeader();
        header.setBackground(Color.white);
        header.setForeground(new Color(153,0,0));
        header.setFont(new Font("Monospaced", Font.ROMAN_BASELINE, 18));
    }
    
    public void panelSwitch(Component comp)
    {
        pnlBase.removeAll(); 
        pnlBase.add(comp);
        pnlBase.repaint();
        pnlBase.revalidate();
    }
    
    public void setComponentColor(Component comp){
        comp.setBackground(new Color(146, 201, 118));
    }
    
    public void resetComponentColor(Component comp){
        comp.setBackground(new Color(76, 161, 66));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sideNavPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        navPlantSetup = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        navSchedule = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        navCure = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        navReport = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        navDashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblFarmerType = new javax.swing.JLabel();
        lblFarmerId = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlBase = new javax.swing.JLayeredPane();
        pnlNotification = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlPlantSetup = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        comboPlantName = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlantSetup = new javax.swing.JTable();
        comboPlantId = new javax.swing.JComboBox<>();
        pnlPersonalSchedule = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePersonalSchedule = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        comboPersonalSchedulePlantName = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        jLabel47 = new javax.swing.JLabel();
        comboPersonalSchedulePlantId = new javax.swing.JComboBox<>();
        jLabel55 = new javax.swing.JLabel();
        pnlDiseaseCure = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDisease = new javax.swing.JTable();
        jLabel56 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        pnlReport = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Panel");
        setName("User Panel"); // NOI18N

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideNavPanel.setBackground(new java.awt.Color(105, 190, 93));
        sideNavPanel.setPreferredSize(new java.awt.Dimension(290, 462));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farmer.png"))); // NOI18N

        navPlantSetup.setBackground(new java.awt.Color(76, 161, 66));
        navPlantSetup.setPreferredSize(new java.awt.Dimension(174, 43));
        navPlantSetup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navPlantSetupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navPlantSetupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navPlantSetupMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rake.png"))); // NOI18N
        jLabel6.setText("Plant Setup");

        javax.swing.GroupLayout navPlantSetupLayout = new javax.swing.GroupLayout(navPlantSetup);
        navPlantSetup.setLayout(navPlantSetupLayout);
        navPlantSetupLayout.setHorizontalGroup(
            navPlantSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPlantSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navPlantSetupLayout.setVerticalGroup(
            navPlantSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPlantSetupLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navSchedule.setBackground(new java.awt.Color(76, 161, 66));
        navSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navScheduleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navScheduleMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jLabel7.setText("Personal Schedule");

        javax.swing.GroupLayout navScheduleLayout = new javax.swing.GroupLayout(navSchedule);
        navSchedule.setLayout(navScheduleLayout);
        navScheduleLayout.setHorizontalGroup(
            navScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navScheduleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        navScheduleLayout.setVerticalGroup(
            navScheduleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        navCure.setBackground(new java.awt.Color(76, 161, 66));
        navCure.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navCureMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navCureMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navCureMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/germs.png"))); // NOI18N
        jLabel8.setText("Disease & Cure");

        javax.swing.GroupLayout navCureLayout = new javax.swing.GroupLayout(navCure);
        navCure.setLayout(navCureLayout);
        navCureLayout.setHorizontalGroup(
            navCureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navCureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navCureLayout.setVerticalGroup(
            navCureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        navReport.setBackground(new java.awt.Color(76, 161, 66));
        navReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navReportMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jLabel9.setText("History & Reports");

        javax.swing.GroupLayout navReportLayout = new javax.swing.GroupLayout(navReport);
        navReport.setLayout(navReportLayout);
        navReportLayout.setHorizontalGroup(
            navReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navReportLayout.setVerticalGroup(
            navReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Welcome Mr. ____________");

        navDashboard.setBackground(new java.awt.Color(76, 161, 66));
        navDashboard.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                navDashboardMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                navDashboardMouseMoved(evt);
            }
        });
        navDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDashboardMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checklist.png"))); // NOI18N
        jLabel5.setText("   Dashboard");

        javax.swing.GroupLayout navDashboardLayout = new javax.swing.GroupLayout(navDashboard);
        navDashboard.setLayout(navDashboardLayout);
        navDashboardLayout.setHorizontalGroup(
            navDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navDashboardLayout.setVerticalGroup(
            navDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navDashboardLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFarmerType.setText("Farmer");

        lblFarmerId.setText("1");

        javax.swing.GroupLayout sideNavPanelLayout = new javax.swing.GroupLayout(sideNavPanel);
        sideNavPanel.setLayout(sideNavPanelLayout);
        sideNavPanelLayout.setHorizontalGroup(
            sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideNavPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(sideNavPanelLayout.createSequentialGroup()
                .addGroup(sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(navReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navCure, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navSchedule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(navPlantSetup, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(navDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(sideNavPanelLayout.createSequentialGroup()
                .addGroup(sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sideNavPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3))
                    .addGroup(sideNavPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblFarmerType)
                        .addGap(49, 49, 49)
                        .addComponent(lblFarmerId)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideNavPanelLayout.setVerticalGroup(
            sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideNavPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(navDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navPlantSetup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navCure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(navReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addGroup(sideNavPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFarmerType)
                    .addComponent(lblFarmerId))
                .addGap(42, 42, 42))
        );

        mainPanel.add(sideNavPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 640));

        headerPanel.setBackground(new java.awt.Color(245, 244, 246));
        headerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Cultivator Assistant");
        headerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vegetables (1).png"))); // NOI18N
        headerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 70, -1));

        mainPanel.add(headerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 900, -1));

        pnlBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102)));
        pnlBase.setLayout(new javax.swing.OverlayLayout(pnlBase));

        pnlNotification.setBackground(new java.awt.Color(255, 255, 255));
        pnlNotification.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jPanel11.setBackground(new java.awt.Color(255, 235, 151));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rewind-time.png"))); // NOI18N
        jLabel13.setText("Wrok Pending For Today");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel19.setText("Step 1: put Fertilizer");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel20.setText("Step 1: weep out extras");

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel27)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pnlNotification.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 360, 150));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jPanel15.setBackground(new java.awt.Color(184, 236, 166));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time-passing.png"))); // NOI18N
        jLabel15.setText("Wrok Pending For Tomorrow");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel2.setText("Step 2: Seed plants");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/warning.png"))); // NOI18N
        jLabel18.setText("Step 1: Water plants");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checked.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)))
                .addGap(53, 53, 53))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(177, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jLabel18)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        pnlNotification.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 360, 150));

        jLabel25.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel25.setText("Date: 01/03/2018");
        pnlNotification.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(245, 244, 246));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel30.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel30.setText("Click on the tick mark if step is completed.");

        jLabel31.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel31.setText("If you need any suggestion, click on the question mark.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNotification.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 100));

        jPanel7.setBackground(new java.awt.Color(76, 161, 66));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel7MouseMoved(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checklist.png"))); // NOI18N
        jLabel10.setText("Dashboard");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 781, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlNotification.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        pnlBase.add(pnlNotification);

        pnlPlantSetup.setBackground(new java.awt.Color(255, 255, 255));
        pnlPlantSetup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel32.setText("Select Plant Name :");
        pnlPlantSetup.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jPanel8.setBackground(new java.awt.Color(70, 147, 21));
        jPanel8.setPreferredSize(new java.awt.Dimension(131, 43));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rake.png"))); // NOI18N
        jLabel11.setText("Plant Setup");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 131, 30));

        pnlPlantSetup.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jLabel34.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel34.setText("Date: 01/03/2018");
        pnlPlantSetup.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jPanel20.setBackground(new java.awt.Color(245, 244, 246));
        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel45.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel45.setText("Click on the tick mark if step is completed.");

        jLabel46.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel46.setText("If you need any suggestion, click on the question mark.");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel45)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPlantSetup.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 100));

        jPanel2.setBackground(new java.awt.Color(217, 235, 249));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButton1.setText("Add New Plant");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlPlantSetup.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 150, 30));

        jPanel3.setBackground(new java.awt.Color(217, 235, 249));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-arrows.png"))); // NOI18N
        jButton3.setText("Update Plant");
        jButton3.setToolTipText("To update 1st select a row");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        pnlPlantSetup.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 140, 30));

        comboPlantName.setBackground(new java.awt.Color(217, 235, 249));
        comboPlantName.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        comboPlantName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        comboPlantName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        comboPlantName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPlantNameItemStateChanged(evt);
            }
        });
        pnlPlantSetup.add(comboPlantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablePlantSetup.setAutoCreateRowSorter(true);
        tablePlantSetup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablePlantSetup.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tablePlantSetup.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Days", "Steps"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePlantSetup.setGridColor(new java.awt.Color(255, 255, 255));
        tablePlantSetup.setRowHeight(25);
        tablePlantSetup.setSelectionBackground(new java.awt.Color(204, 232, 181));
        tablePlantSetup.setSelectionForeground(new java.awt.Color(153, 0, 0));
        jScrollPane2.setViewportView(tablePlantSetup);
        if (tablePlantSetup.getColumnModel().getColumnCount() > 0) {
            tablePlantSetup.getColumnModel().getColumn(0).setMinWidth(0);
            tablePlantSetup.getColumnModel().getColumn(0).setMaxWidth(0);
            tablePlantSetup.getColumnModel().getColumn(1).setMinWidth(70);
            tablePlantSetup.getColumnModel().getColumn(1).setMaxWidth(80);
        }

        pnlPlantSetup.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 840, 360));

        pnlPlantSetup.add(comboPlantId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 20));

        pnlBase.add(pnlPlantSetup);

        pnlPersonalSchedule.setBackground(new java.awt.Color(255, 255, 255));
        pnlPersonalSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(70, 147, 21));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        jLabel12.setText("Personal Schedule");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(797, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlPersonalSchedule.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jLabel33.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel33.setText("Date: 01/03/2018");
        pnlPersonalSchedule.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, -1));

        jPanel16.setBackground(new java.awt.Color(245, 244, 246));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel37.setText("Click on the tick mark if step is completed.");

        jLabel38.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel38.setText("If you need any suggestion, click on the question mark.");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPersonalSchedule.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 100));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tablePersonalSchedule.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tablePersonalSchedule.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tablePersonalSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Steps", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePersonalSchedule.setGridColor(new java.awt.Color(255, 255, 255));
        tablePersonalSchedule.setRowHeight(25);
        tablePersonalSchedule.setSelectionBackground(new java.awt.Color(204, 232, 181));
        jScrollPane1.setViewportView(tablePersonalSchedule);
        if (tablePersonalSchedule.getColumnModel().getColumnCount() > 0) {
            tablePersonalSchedule.getColumnModel().getColumn(0).setMinWidth(150);
            tablePersonalSchedule.getColumnModel().getColumn(0).setMaxWidth(200);
            tablePersonalSchedule.getColumnModel().getColumn(2).setMinWidth(120);
            tablePersonalSchedule.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        pnlPersonalSchedule.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 840, 340));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Personal Schedule"));

        jLabel48.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel48.setText("Select Plant : ");

        comboPersonalSchedulePlantName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPersonalSchedulePlantNameItemStateChanged(evt);
            }
        });

        jLabel53.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel53.setText("Start Date: ");

        jLabel47.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel47.setText("Search");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboPersonalSchedulePlantName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboPersonalSchedulePlantId, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboPersonalSchedulePlantName)
                    .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboPersonalSchedulePlantId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPersonalSchedule.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 670, 50));

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel55.setText("Start New Process");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        pnlPersonalSchedule.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 140, 40));

        pnlBase.add(pnlPersonalSchedule);

        pnlDiseaseCure.setBackground(new java.awt.Color(255, 255, 255));
        pnlDiseaseCure.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(70, 147, 21));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/germs.png"))); // NOI18N
        jLabel16.setText("Disease & Cure");
        jPanel12.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, -1));

        pnlDiseaseCure.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jPanel17.setBackground(new java.awt.Color(245, 244, 246));
        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel39.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel39.setText("Click on the tick mark if step is completed.");

        jLabel40.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel40.setText("If you need any suggestion, click on the question mark.");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel39)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDiseaseCure.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 100));

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(153, 153, 153));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        pnlDiseaseCure.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 220, 30));

        jLabel49.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel49.setText("Katui Poka");
        pnlDiseaseCure.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlDiseaseCure.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(217, 235, 249));

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setLabel("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlDiseaseCure.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 100, 30));

        jLabel50.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel50.setText("Date: 01/03/2018");
        pnlDiseaseCure.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel51.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel51.setText("Disease Name:");
        pnlDiseaseCure.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel52.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel52.setText("Cure>>>>");
        pnlDiseaseCure.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel54.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel54.setText("Roten Leaf");
        pnlDiseaseCure.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tableDisease.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableDisease.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        tableDisease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Symptoms"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableDisease.setGridColor(new java.awt.Color(204, 204, 204));
        tableDisease.setRowHeight(25);
        tableDisease.setSelectionBackground(new java.awt.Color(204, 232, 181));
        tableDisease.setSelectionForeground(new java.awt.Color(153, 0, 0));
        jScrollPane3.setViewportView(tableDisease);
        if (tableDisease.getColumnModel().getColumnCount() > 0) {
            tableDisease.getColumnModel().getColumn(0).setMinWidth(0);
            tableDisease.getColumnModel().getColumn(0).setMaxWidth(0);
            tableDisease.getColumnModel().getColumn(1).setMinWidth(200);
            tableDisease.getColumnModel().getColumn(1).setMaxWidth(250);
        }

        pnlDiseaseCure.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 780, 250));

        jLabel56.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel56.setText("Symptoms:");
        pnlDiseaseCure.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel5.setBackground(new java.awt.Color(217, 235, 249));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButton4.setText("Add Disease Cure");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlDiseaseCure.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 150, 30));

        jPanel6.setBackground(new java.awt.Color(217, 235, 249));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update-arrows.png"))); // NOI18N
        jButton5.setText("Update ");
        jButton5.setToolTipText("To update 1st select a row");
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton5)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jButton5))
        );

        pnlDiseaseCure.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 140, 30));

        pnlBase.add(pnlDiseaseCure);

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));
        pnlReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(70, 147, 21));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/report.png"))); // NOI18N
        jLabel17.setText("History & Reports");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(714, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlReport.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        jLabel36.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel36.setText("Select by Date:");
        pnlReport.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        jPanel18.setBackground(new java.awt.Color(245, 244, 246));
        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(0));

        jLabel41.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel41.setText("Click on the tick mark if step is completed.");

        jLabel42.setFont(new java.awt.Font("Segoe UI Semilight", 0, 14)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tips.png"))); // NOI18N
        jLabel42.setText("If you need any suggestion, click on the question mark.");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(517, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel41)
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReport.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 900, 100));

        jLabel57.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel57.setText("Select By Plant:");
        pnlReport.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabel58.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel58.setText("Date: 01/03/2018");
        pnlReport.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jComboBox3.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReport.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        jComboBox4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlReport.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable4.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Steps", "Date", "Completed", "Not Completed"
            }
        ));
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.setSelectionBackground(new java.awt.Color(204, 232, 181));
        jScrollPane4.setViewportView(jTable4);
        if (jTable4.getColumnModel().getColumnCount() > 0) {
            jTable4.getColumnModel().getColumn(2).setHeaderValue("Completed");
            jTable4.getColumnModel().getColumn(3).setHeaderValue("Not Completed");
        }

        pnlReport.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 780, 290));

        pnlBase.add(pnlReport);

        mainPanel.add(pnlBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 900, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navPlantSetupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navPlantSetupMouseClicked
        // TODO add your handling code here:
        
        panelSwitch(pnlPlantSetup);
        //comboPlantId.setVisible(false);
        tableHeader(tablePlantSetup);
        tableBody(tablePlantSetup);
        comboPlantName.removeAllItems();
        comboPlantId.removeAllItems();
        //DefaultTableModel model = (DefaultTableModel) tablePlantSetup.getModel();
        //model.setRowCount(0);
        HashMap<Integer,HashMap> plant_setup = new HashMap<>();

        plant_setup = dc.getAllInformation("plant_setup_mst_tb","");
      
        for (Object key : plant_setup.keySet())
        {
            comboPlantId.addItem(plant_setup.get(key).get("id").toString());
            comboPlantName.addItem(plant_setup.get(key).get("plant_name").toString());
            
            //model.addRow(new Object[]{plant_setup.get(key).get("id"),plant_setup.get(key).get("plant_name"),plant_setup.get(key).get("description")});
        } 
          
    }//GEN-LAST:event_navPlantSetupMouseClicked

    private void navScheduleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navScheduleMouseClicked
        // TODO add your handling code here:
        panelSwitch(pnlPersonalSchedule);
        
        tableHeader(tablePersonalSchedule);
        tableBody(tablePersonalSchedule);
        comboPersonalSchedulePlantName.removeAllItems();
        comboPersonalSchedulePlantId.removeAllItems();
        //DefaultTableModel model = (DefaultTableModel) tablePlantSetup.getModel();
        //model.setRowCount(0);
        HashMap<Integer,HashMap> personal_schedule = new HashMap<>();

        personal_schedule = dc.getAllInformation("personal_schedule_tb_v"," where farmer_id = "+ lblFarmerId.getText() + " and action = 0 group by plant_id");
      
        for (Object key : personal_schedule.keySet())
        {
            System.out.println(personal_schedule.get(key).get("plant_name").toString());
            comboPersonalSchedulePlantId.addItem(personal_schedule.get(key).get("plant_id").toString());
            comboPersonalSchedulePlantName.addItem(personal_schedule.get(key).get("plant_name").toString());
            
            //model.addRow(new Object[]{plant_setup.get(key).get("id"),plant_setup.get(key).get("plant_name"),plant_setup.get(key).get("description")});
        }
        
    }//GEN-LAST:event_navScheduleMouseClicked

    private void navCureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCureMouseClicked
        // TODO add your handling code here:
        panelSwitch(pnlDiseaseCure);
        tableHeader(tableDisease);
        tableBody(tableDisease);
        DefaultTableModel model = (DefaultTableModel) tableDisease.getModel();
        model.setRowCount(0);
        HashMap<Integer,HashMap> disease_cure = new HashMap<>();
        

        disease_cure = dc.getAllInformation("disease_tb","");
      
        for (Object key : disease_cure.keySet())
        {
            model.addRow(new Object[]{disease_cure.get(key).get("id"),disease_cure.get(key).get("name"),disease_cure.get(key).get("symptoms")});  
        }      
        
    }//GEN-LAST:event_navCureMouseClicked

    private void navReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navReportMouseClicked
        // TODO add your handling code here:
        panelSwitch(pnlReport);
    }//GEN-LAST:event_navReportMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormPlantSetup fps = new FormPlantSetup();
        fps.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseMoved

    private void navDashboardMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseMoved
        // TODO add your handling code here:
        
        

    }//GEN-LAST:event_navDashboardMouseMoved

    private void navDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseClicked
        // TODO add your handling code here:
        panelSwitch(pnlNotification);
    }//GEN-LAST:event_navDashboardMouseClicked

    private void navDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseEntered
        // TODO add your handling code here:
        setComponentColor(navDashboard);
    }//GEN-LAST:event_navDashboardMouseEntered

    private void navDashboardMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_navDashboardMouseDragged

    private void navDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseExited
        // TODO add your handling code here:
        resetComponentColor(navDashboard);
    }//GEN-LAST:event_navDashboardMouseExited

    private void navPlantSetupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navPlantSetupMouseEntered
        // TODO add your handling code here:
        setComponentColor(navPlantSetup);
    }//GEN-LAST:event_navPlantSetupMouseEntered

    private void navPlantSetupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navPlantSetupMouseExited
        // TODO add your handling code here:
        resetComponentColor(navPlantSetup);
    }//GEN-LAST:event_navPlantSetupMouseExited

    private void navScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navScheduleMouseEntered
        // TODO add your handling code here:
        setComponentColor(navSchedule);
    }//GEN-LAST:event_navScheduleMouseEntered

    private void navScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navScheduleMouseExited
        // TODO add your handling code here:
        resetComponentColor(navSchedule);
    }//GEN-LAST:event_navScheduleMouseExited

    private void navCureMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCureMouseEntered
        // TODO add your handling code here:
        setComponentColor(navCure);
    }//GEN-LAST:event_navCureMouseEntered

    private void navCureMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCureMouseExited
        // TODO add your handling code here:
        resetComponentColor(navCure);
    }//GEN-LAST:event_navCureMouseExited

    private void navReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navReportMouseEntered
        // TODO add your handling code here:
        setComponentColor(navReport);
    }//GEN-LAST:event_navReportMouseEntered

    private void navReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navReportMouseExited
        // TODO add your handling code here:
        resetComponentColor(navReport);
    }//GEN-LAST:event_navReportMouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = comboPlantId.getItemAt(comboPlantName.getSelectedIndex());
        FormPlantSetup fps = new FormPlantSetup(id);
        fps.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DiseaseCure fps = new DiseaseCure();
        fps.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void comboPlantNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPlantNameItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablePlantSetup.getModel();
        model.setRowCount(0);
        HashMap<Integer,HashMap> plant_setup = new HashMap<>();
        String id = comboPlantId.getItemAt(comboPlantName.getSelectedIndex());
//        if(id == null)
//        {
//            id = comboPlantId.getItemAt(0);
//        }
        System.out.println(id);
        System.out.println(id);
        plant_setup = dc.getAllInformation("plant_setup_chd_tb"," where plant_id = "+id);
      
        for (Object key : plant_setup.keySet())
        {
            //comboPlantName.addItem(plant_setup.get(key).get("plant_name").toString());
            model.addRow(new Object[]{plant_setup.get(key).get("id"),plant_setup.get(key).get("days"),plant_setup.get(key).get("steps_desc")});
        }
    }//GEN-LAST:event_comboPlantNameItemStateChanged

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        StartCultivation sc = new StartCultivation(lblFarmerId.getText());
        sc.setVisible(true);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void comboPersonalSchedulePlantNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPersonalSchedulePlantNameItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tablePersonalSchedule.getModel();
        model.setRowCount(0);
        HashMap<Integer,HashMap> personal_schedule = new HashMap<>();
        String id = comboPersonalSchedulePlantId.getItemAt(comboPersonalSchedulePlantName.getSelectedIndex());

        personal_schedule = dc.getAllInformation("personal_schedule_tb_v"," where farmer_id = "+ lblFarmerId.getText() + " and plant_id = " + id + " and action = 0");
      
        for (Object key : personal_schedule.keySet())
        {
            //comboPlantName.addItem(plant_setup.get(key).get("plant_name").toString());
            String action="Completed";
            if(personal_schedule.get(key).get("action").equals("0"))
            {
                action = "Not completed";
            }
            model.addRow(new Object[]{personal_schedule.get(key).get("date"),personal_schedule.get(key).get("step_desc"),action});
        }
    }//GEN-LAST:event_comboPersonalSchedulePlantNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboPersonalSchedulePlantId;
    private javax.swing.JComboBox<String> comboPersonalSchedulePlantName;
    private javax.swing.JComboBox<String> comboPlantId;
    private javax.swing.JComboBox<String> comboPlantName;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblFarmerId;
    private javax.swing.JLabel lblFarmerType;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navCure;
    private javax.swing.JPanel navDashboard;
    private javax.swing.JPanel navPlantSetup;
    private javax.swing.JPanel navReport;
    private javax.swing.JPanel navSchedule;
    private javax.swing.JLayeredPane pnlBase;
    private javax.swing.JPanel pnlDiseaseCure;
    private javax.swing.JPanel pnlNotification;
    private javax.swing.JPanel pnlPersonalSchedule;
    private javax.swing.JPanel pnlPlantSetup;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel sideNavPanel;
    private javax.swing.JTable tableDisease;
    private javax.swing.JTable tablePersonalSchedule;
    private javax.swing.JTable tablePlantSetup;
    // End of variables declaration//GEN-END:variables
}
