/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agricultureproject;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dead
 */
public class StartCultivation extends javax.swing.JFrame {

    /**
     * Creates new form StartCultivation
     */
    DatabaseConnection dc = new DatabaseConnection();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Calendar cal = Calendar.getInstance();
    public StartCultivation(String id) {
        initComponents();
        getAllPlantInformation();    
    }
    
    public void getAllPlantInformation()
    {
        comboNewPlantName.removeAllItems();
        comboNewPlantId.removeAllItems();
        HashMap<Integer,HashMap> plant_setup = new HashMap<>();

        plant_setup = dc.getAllInformation("plant_setup_mst_tb","");
      
        for (Object key : plant_setup.keySet())
        {
            comboNewPlantId.addItem(plant_setup.get(key).get("id").toString());
            comboNewPlantName.addItem(plant_setup.get(key).get("plant_name").toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel55 = new javax.swing.JLabel();
        comboNewPlantName = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        comboNewPlantId = new javax.swing.JComboBox<>();
        lblGenerate = new javax.swing.JLabel();
        lblFarmerId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel55.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel55.setText("Select Plant : ");

        jLabel59.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel59.setText("Start Date: ");

        lblGenerate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblGenerate.setText("Generate ");
        lblGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGenerateMouseClicked(evt);
            }
        });

        lblFarmerId.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGenerate)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel59)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboNewPlantId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFarmerId))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboNewPlantName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboNewPlantId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFarmerId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNewPlantName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGenerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGenerateMouseClicked
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog (null, "Are you sure?","WARNING",JOptionPane.YES_NO_OPTION);

        if(dialogButton == JOptionPane.YES_OPTION)
        {
            HashMap<Integer,HashMap> plant_setup = new HashMap<>();
            HashMap generate_schedule = new HashMap();
            String id = comboNewPlantId.getItemAt(comboNewPlantName.getSelectedIndex());
            String startDate = sdf.format(dateStart.getDate());

            // add Date

            Date date = null,futureDate;
            try {
                date = sdf.parse(startDate); 

            } catch (ParseException ex) {
                Logger.getLogger(StartCultivation.class.getName()).log(Level.SEVERE, null, ex);
            }




            plant_setup = dc.getAllInformation("plant_setup_chd_tb"," where plant_id = " +id );

            for (Object key : plant_setup.keySet())
            {
                System.out.println(plant_setup.get(key).get("days"));
                System.out.println(plant_setup.get(key).get("steps_desc"));
                cal.setTime(date);
                cal.add(Calendar.DAY_OF_MONTH,  Integer.parseInt(plant_setup.get(key).get("days").toString())); // Add 30 days
                //futureDate = cal.getTime();

                generate_schedule.put("date", sdf.format(cal.getTime()));
                generate_schedule.put("plant_id", id);
                generate_schedule.put("farmer_id", lblFarmerId.getText());
                generate_schedule.put("step_desc", plant_setup.get(key).get("steps_desc"));
                dc.insertData("personal_schedule_tb",generate_schedule);
            }
        }  
    }//GEN-LAST:event_lblGenerateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartCultivation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartCultivation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartCultivation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartCultivation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StartCultivation().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboNewPlantId;
    private javax.swing.JComboBox<String> comboNewPlantName;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel lblFarmerId;
    private javax.swing.JLabel lblGenerate;
    // End of variables declaration//GEN-END:variables
}
